[[script]]
url        = "https://github.com/tearne/tok.git"
sha        = "e95a277d176f664485e5806e6c05768af3470e03"
entrypoint = "tok.py"
rename     = "tok"

[[script]]
url   = "https://github.com/tearne/grit"
sha   = "4f0f94098fe7878b21452c3648d89f2053659075"
build = "cargo"
